
male_first_names = [
    "Aleksandr", "Aleksei", "Anatoliy", "Andrey", "Artem", "Anton", "Arseny", "Artemiy", "Arkadiy",
    "Boris",
    "Vladimir", "Victor", "Vsevolod", "Vadim", "Valery", "Vyacheslav",
    "Gleb", "Grigory", "Gennady",
    "Denis", "Dmitriy", "Danila",
    "Evgeny", "Emil", "Egor",
    "Zahar", "Zaur",
    "Ivan", "Ilya", "Igor",
    "Kirill", "Konstantin",
    "Leonid",
    "Maksim", "Mikhail", "Makar", "Matvei",
    "Nikolay", "Nikita",
    "Oleg",
    "Pavel", "Petr",
    "Roman", "Rodion", "Ruslan",
    "Sergey", "Stanislav", "Semyon", "Stepan", "Slava", "Serafim",
    "Timofey", "Timur", "Tikhon",
    "Fedor", "Felix",
    "Yaroslav", "Yevgeny", "Yuri",  "Yakov",
]

female_first_names = [
    "Alena", "Anastasiya", "Anna", "Arina", "Anfisa", "Alina", "Angelina", "Aida", "Alla", "Alevtina",
    "Valentina", "Vera", "Veronika", "Victoria", "Vasilisa", "Valeriya",
    "Galina", "Gulnara",
    "Daria",
    "Ekaterina", "Elena", "Evelina", "Eugenia", "Emilia", "Efrosiniya",
    "Zinaida",
    "Irina", "Inna",
    "Kira", "Ksenia", "Kristina",
    "Larisa", "Ludmila", "Lilia", "Lyubov", "Lera",
    "Marina", "Maria", "Mila", "Margarita",
    "Nadezhda", "Natalya", "Nina", "Nika",
    "Olga", "Oksana",
    "Polina",
    "Regina", "Rita", "Raisa", "Rimma", "Renata", "Rosa",
    "Svetlana", "Sofia",
    "Tatiana", "Tamara", "Taisiya",
    "Ulyana",
    "Feodora", "Faina",
    "Juliana",
    "Yana", "Yekaterina", "Yulia",
]

male_last_names = [
    "Abrosimov", "Aleksandrov", "Alekseev", "Andreev", "Artemyev", "Babikov",
    "Bakhmetev", "Balakirev", "Baranov", "Belov", "Belyakov", "Borodin",
    "Borovik", "Bulatov", "Burkov", "Chekhov", "Danilov", "Dmitriev",
    "Dobrynin", "Dudkin", "Epiphanyev", "Ershov", "Fedorov",
    "Gavrilov", "Gorbachev", "Gorodetsky", "Grigoryev", "Ilyin", "Ivanov",
    "Kachin", "Karpov", "Karpenko", "Kirov", "Kiselyov", "Klimov",
    "Kobzev", "Korolev", "Krasnov", "Kuznetsov", "Lebedev", "Leontyev",
    "Markov", "Matveev", "Medvedev", "Mikhailov", "Morozov", "Nalivayko",
    "Nazarov", "Nesterenko", "Novikov", "Obolensky", "Orlov", "Pavlov",
    "Petrov", "Rogozin", "Romanov", "Rublev", "Samsonov", "Semenov",
    "Shestakov", "Shilov", "Sokolov", "Sosnitsky", "Starodubtsev", "Tarasov",
    "Timofeyev", "Tikhonov", "Ustinov", "Vasiliev", "Vinogradov",
    "Volkov", "Voloshin", "Vrublev", "Zaytsev", "Zelengin", "Zhuravlev",
    "Abdulin", "Alferov", "Antipov", "Apanovich", "Barinov", "Bashkov",
    "Bersenev", "Blinov", "Bolshakov", "Borovikov", "Burdin", "Chaban",
    "Chikine", "Doroshenko", "Dovgan", "Dudaryov", "Erofeev",
    "Gavrilchenko", "Golikov", "Gorbunov", "Grinenko",
    "Gusarov", "Ivanov", "Kalenik", "Kalugin", "Karavaev", "Kazakov",
    "Kozlov", "Kraev", "Kulakov", "Kuzmin", "Likhanov", "Makarov",
    "Malyshev", "Matyushkin", "Mishin", "Moiseev", "Nechaev", "Nikolaev",
    "Obukhov", "Okhlopkov", "Orekhov", "Ostroumov", "Panov", "Pavlenko",
    "Platonov", "Polunin", "Popov", "Prokhorov", "Rassudov", "Serov",
    "Sokolov", "Sopov", "Tikhonenkov", "Trusov", "Uvarov", "Veselov",
    "Vinokurov", "Vorobyov", "Yakshin", "Yermakov", "Yermollov", "Zarubin",
    "Zubkov", "Zverev"
]


female_last_names = [
    "Abrosimova", "Aleksandrovna", "Alekseeva", "Andreeva", "Artemyeva", "Babikova",
    "Bakhmeteva", "Balakireva", "Baranova", "Belova", "Belyakova", "Borodina",
    "Borovikova", "Bulatova", "Burkova", "Chekhova", "Danilova", "Dmitrieva",
    "Dobrynina", "Dudkina", "Epiphanyeva", "Ershova", "Fedorova",
    "Gavrilova", "Gorbacheva", "Gorodetskya", "Grigoryeva", "Ilyina", "Ivanova",
    "Kachian", "Karpova", "Karpenko", "Kirova", "Kiselyova", "Klimova",
    "Kobzeva", "Koroleva", "Krasnova", "Kuznetsova", "Lebedeva", "Leontyeva",
    "Markova", "Matveeva", "Medvedeva", "Mikhailova", "Morozova", "Nalivayko",
    "Nazarova", "Nesterenko", "Novikova", "Obolenskya", "Orlova", "Pavlova",
    "Petrova", "Rogozina", "Romanova", "Rubleva", "Samsonova", "Semenova",
    "Shestakova", "Shilova", "Sokolova", "Sosnitskya", "Starodubtseva", "Tarasova",
    "Timofeyeva", "Tikhonova", "Ustinova", "Vasilieva", "Vinogradova",
    "Volkova", "Voloshina", "Vrubleva", "Zaytseva", "Zelengina", "Zhuravleva",
    "Abdulina", "Alferova", "Antipova", "Apanovichna", "Barinova", "Bashkoav",
    "Berseneva", "Blinova", "Bolshakova", "Borovikova", "Burdina", "Chaban",
    "Chikine", "Doroshenko", "Dovgan", "Dudaryova", "Erofeeva",
     "Gavrilchenko", "Golikova", "Gorbunova", "Grinenko",
    "Gusarova", "Ivanova", "Kalenik", "Kalugina", "Karavaeva", "Kazakova",
    "Kozlova", "Kraeva", "Kulakova", "Kuzmina", "Likhanova", "Makarova",
    "Malysheva", "Matyushkina", "Mishina", "Moiseeva", "Nechaeva", "Nikolaeva",
    "Obukhova", "Okhlopkova", "Orekhova", "Ostroumova", "Panova", "Pavlenko",
    "Platonova", "Polunina", "Popova", "Prokhorova", "Rassudova", "Serova",
    "Sokolova", "Sopova", "Tikhonenkova", "Trusova", "Uvarovaa", "Veselova",
    "Vinokurova", "Vorobyova", "Yakshina", "Yermakova", "Yermollova", "Zarubina",
    "Zubkova", "Zvereva"
]

male_patronymics = [
    "Aleksandrovich", "Dmitrievich", "Ivanovich", "Sergeevich", "Maximovich",
    "Nikolayevich", "Vladimirovich", "Andreevich", "Pavlovich", "Yaroslavovich",
    "Fyodorovich", "Alekseevich", "Kirillovich", "Anatolievich", "Ilyich",
    "Gennadievich", "Romanovich", "Vyacheslavovich", "Mikhailovich", "Leonidovich",
    "Denisovich", "Borisovich", "Artemovich", "Evgenievich", "Timofeevich",
    "Viktorovich", "Semyonovich", "Stanislavovich", "Antonovich", "Olegovich",
    "Arkadevich", "Igorevich", "Grigoryevich", "Alexanderovich", "Stepanovich",
    "Nikitovich", "Valeryevich", "Alexeevich", "Makarevich", "Romanovich",
    "Evgenievich", "Dmitriyevich", "Radikovich", "Ruslanovich", "Timurlanovich",
    "Zaurovich", "Arsenievich", "Danilovich", "Tikhonovich", "Viktorovich",
    "Vsevolodovich", "Yevgenievich", "Petrovich", "Felixovich", "Matveyevich",
    "Vadimovich", "Olegovich", "Sergeyevich", "Svetoslavovich", "Leonidovich",
]

female_patronymics = [
    "Aleksandrovna", "Dmitrievna", "Ivanovna", "Sergeevna", "Maximovna",
    "Nikolayevna", "Vladimirovna", "Andreevna", "Pavlovna", "Yaroslavovna",
    "Fyodorovna", "Alekseevna", "Kirillovna", "Anatolievna", "Ilyinichna",
    "Gennadevna", "Romanovna", "Vyacheslavovna", "Mikhailovna", "Leonidovna",
    "Denisovna", "Borisovna", "Artemovna", "Evgenievna", "Timofeevna",
    "Viktorovna", "Semyonovna", "Stanislavovna", "Antonovna", "Olegovna",
    "Arkadevna", "Igorevna", "Grigoryevna", "Alexandrovna", "Stepanovna",
    "Nikitovna", "Valeryevna", "Alexeevna", "Makarevna", "Romanovna",
    "Evgenievna", "Dmitriyevna", "Radikovna", "Ruslanovna", "Timurlanova",
    "Zaurovna", "Arsenievna", "Danilovna", "Tikhonovna", "Viktorovna",
    "Vsevolodovna", "Yevgenievna", "Petrovna", "Felixovna", "Matveyevna",
    "Vadimovna", "Sergeyevna", "Svetoslavovna", "Leonidovna", "Maksimovna",
]
